version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel11-app
        container_name: laravel11-app
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    web:
        image: nginx:stable
        container_name: laravel11-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel11-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
